CREATE SCHEMA IF NOT EXISTS radb DEFAULT CHARACTER SET utf8;
USE radb;

CREATE TABLE IF NOT EXISTS wallet (
  id INT PRIMARY KEY AUTO_INCREMENT,
  balance INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user (
  id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
  login VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL,
  role ENUM('CLIENT', 'MASTER', 'MANAGER', 'ADMIN') NOT NULL
);

CREATE TABLE IF NOT EXISTS client (
  id INT PRIMARY KEY AUTO_INCREMENT,
  wallet_id INT NOT NULL REFERENCES wallet (id),
  user_id INT NOT NULL REFERENCES user (id)
);

CREATE TABLE IF NOT EXISTS request (
  id INT PRIMARY KEY AUTO_INCREMENT,
  creation_date DATETIME NOT NULL,
  status ENUM('NEW', 'WAIT_FOR_PAYMENT', 'PAID', 'CANCELLED', 'IN_PROCESS', 'DONE') NOT NULL,
  description TEXT NOT NULL,
  completion_date DATETIME NULL,
  user_review TEXT NULL,
  cancel_reason TEXT NULL,
  master_id INT NULL,
  price INT NULL,
  client_id INT NOT NULL REFERENCES client (id)
);

CREATE TABLE IF NOT EXISTS payment_record (
  id INT PRIMARY KEY AUTO_INCREMENT,
  date DATETIME NOT NULL,
  destination VARCHAR(50) NULL,
  wallet_id INT NOT NULL REFERENCES wallet (id)
);
