USE radb;

DROP TABLE IF EXISTS payment_record;
DROP TABLE IF EXISTS wallet;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS master;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS role;